---
- name: set concurrent jobs
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: '^concurrent = \d+'
    line: 'concurrent = {{ gitlab_ci_concurrent|default(1) }} '
    create: yes
    owner: root
    group: root
    mode: 'u=rw,go='
  notify: restart gitlab-runner

- name: check registered runner
  command: grep -c 'name = "{{ item.name }}"' /etc/gitlab-runner/config.toml
  register: gitlab_ci_registered_runner_result
  ignore_errors: true
  with_items: "{{ gitlab_ci_runner_registration }}"

- name: register runner
  command: >
    gitlab-runner register -n
    --url {{ item.item.url }}
    --registration-token {{ item.item.token }}
    --name {{ item.item.name }}
    --executor {{ item.item.executor|default('docker') }}
    --locked={{ 'true' if (item.item.locked|default(false)) else 'false' }}
    --docker-image {{ item.item.docker_image|default('python:2.7') }}
    --locked={{ 'true' if item.item.locked|default(false) else 'false' }}
    {{ ' --docker-privileged ' if (item.item.docker_privileged|default(false)) else '' }}

  when: item.stdout == '0'
  with_items: "{{ gitlab_ci_registered_runner_result.results }}"
