---
- name: set concurrent jobs
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: '^concurrent = \d+'
    line: 'concurrent = {{ gitlab_ci_concurrent|default(1) }} '
    create: yes
    owner: root
    group: root
    mode: 'u=rw,go='
  notify: restart gitlab-runner

- name: check registered runner
  command: grep -c 'name = "{{ item.name }}"' /etc/gitlab-runner/config.toml
  register: gitlab_ci_registered_runner_result
  ignore_errors: true
  with_items: "{{ gitlab_ci_runner_registration }}"

- name: register runner
  command: >
    gitlab-runner register -n
    {% for key,value in item.item.iteritems() %}{% if value %}--{{ key|replace('_', '-') }}{% if value is string %} '{{ value }}'{% endif %} {% endif %}{% endfor %}
  when: item.stdout == '0'
  with_items: "{{ gitlab_ci_registered_runner_result.results }}"
